app: vjepa
nodes: 1
tasks_per_node: 1
data:
  dataset_type: VideoDataset
  datasets:
    - ../datasets/drawing-agent-3200/videos/videos_index.csv
  decode_one_clip: true
  batch_size: 4  # Reduced batch size for small GPU
  num_clips: 1
  num_frames: 16
  tubelet_size: 2
  sampling_rate: 4
  crop_size: 56
  patch_size: 4
  pin_mem: true
  num_workers: 4  # Reduced workers for single GPU
  filter_short_videos: false
  clip_duration: null
data_aug:
  auto_augment: false
  motion_shift: false
  random_resize_aspect_ratio:
  - 0.75
  - 1.35
  random_resize_scale:
  - 0.3
  - 1.0
  reprob: 0.0
logging:
  folder: /home/guglielmo/Projects/jepa-experiments/trash
  write_tag: jepa_tiny
loss:
  loss_exp: 1.0
  reg_coeff: 0.0
mask:
  - aspect_ratio:
      - 0.75
      - 1.5
    num_blocks: 8
    spatial_scale:
      - 0.15
      - 0.15
    temporal_scale:
      - 1.0
      - 1.0
    max_temporal_keep: 1.0
    max_keep: null
  - aspect_ratio:
      - 0.75
      - 1.5
    num_blocks: 2
    spatial_scale:
      - 0.7
      - 0.7
    temporal_scale:
      - 1.0
      - 1.0
    max_temporal_keep: 1.0
    max_keep: null
  - mode: time_split
meta:
  load_checkpoint: false
  read_checkpoint: null
  seed: 234
  eval_freq: 100
  use_sdpa: true
  dtype: bfloat16
model:
  model_name: vit_tiny  # Using vit_tiny instead of vit_huge
  pred_depth: 6  # Reduced predictor depth
  pred_embed_dim: 192  # Reduced embedding dimension
  uniform_power: true
  use_mask_tokens: true
  zero_init_mask_tokens: true
optimization:
  ipe: 100  # Reduced iterations per epoch
  ipe_scale: 1.0
  clip_grad: 10.0
  weight_decay: 0.04
  final_weight_decay: 0.4
  epochs: 100  # Reduced number of epochs
  warmup: 10  # Reduced warmup
  start_lr: 0.0002
  lr: 0.0004
  final_lr: 1.0e-06
  ema:
  - 0.998
  - 1.0 