nodes: 1
tasks_per_node: 1
tag: mnist
eval_name: image_classification_frozen
resume_checkpoint: false
data:
  root_path: /home/guglielmo/Projects/datasets/action-drawing-agent/videos_with_action/3200-videos/
  image_folder: curve_lines_dataset/
  num_classes: 2
  resolution: 56
  dataset_name: CURVE_LINES
  normalize_only: true
optimization:
  num_epochs: 60
  batch_size: 32
  weight_decay: 0.001
  lr: 0.001
  start_lr: 0.0001
  final_lr: 0.00001
  warmup: 0.05
  use_bfloat16: true
pretrain:
  model_name: vit_tiny
  checkpoint_key: target_encoder
  clip_duration: null
  frames_per_clip: 16
  tubelet_size: 2
  uniform_power: true
  use_sdpa: true
  use_silu: false
  tight_silu: false
  patch_size: 4
  folder: /home/guglielmo/Projects/experiments_result/action-drawing-agent/action_videos/3200-videos/run1/
  checkpoint: jepa_tiny-latest.pth.tar  # name of pretrained model file inside folder
  write_tag: jepa
